name: Roq Site Deploy

on:
  push:
    branches: [ "cas/draft-deploy" ]   # Switch to the branch which should be deployed to GitHub Pages
  #schedule:
  #  - cron: "0 5 * * *"  # Runs every day at 05:00 UTC to publish scheduled content
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Generate Roq Site
        uses: quarkiverse/quarkus-roq@v1.1
        with:
          site-future: ${{ env.SITE_URL }}
          site-url: ${{ env.SITE_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}   # Used to automatically get the GitHub Pages url
      - name: Set up S3cmd cli tool
        # https://github.com/marketplace/actions/use-s3cmd
        uses: s3-actions/s3cmd@v3.0.0
        with:
          provider: scaleway # default is linode
          region: 'fr-par'
          # bucket_id: ${{ secrets.S3_SCW_BUCKET_ID }}
          access_key: ${{ secrets.SCW_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.SCW_SECRET_ACCESS_KEY }}

      - name: Interact with object storage
        run: |
          cd target/rog &&\
          s3cmd sync --recursive --acl-public . s3://${{ secrets.S3_SCW_BUCKET_ID }}/
          